/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AnnouncementCategory = IDL.Variant({
  'academic' : IDL.Null,
  'event' : IDL.Null,
  'urgent' : IDL.Null,
  'general' : IDL.Null,
});
export const AnnouncementId = IDL.Nat;
export const AdmissionId = IDL.Nat;
export const AdmissionForm = IDL.Record({
  'id' : AdmissionId,
  'parentEmail' : IDL.Text,
  'studentName' : IDL.Text,
  'date' : IDL.Int,
  'parentPhone' : IDL.Text,
  'message' : IDL.Text,
  'parentName' : IDL.Text,
  'gradeApplyingFor' : IDL.Text,
});
export const Announcement = IDL.Record({
  'id' : AnnouncementId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Int,
  'category' : AnnouncementCategory,
});
export const ContactId = IDL.Nat;
export const ContactForm = IDL.Record({
  'id' : ContactId,
  'subject' : IDL.Text,
  'date' : IDL.Int,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, AnnouncementCategory],
      [],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([AnnouncementId], [], []),
  'getAllAdmissionForms' : IDL.Func([], [IDL.Vec(AdmissionForm)], ['query']),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getAnnouncementsByCategory' : IDL.Func(
      [AnnouncementCategory],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'submitAdmissionForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AnnouncementCategory = IDL.Variant({
    'academic' : IDL.Null,
    'event' : IDL.Null,
    'urgent' : IDL.Null,
    'general' : IDL.Null,
  });
  const AnnouncementId = IDL.Nat;
  const AdmissionId = IDL.Nat;
  const AdmissionForm = IDL.Record({
    'id' : AdmissionId,
    'parentEmail' : IDL.Text,
    'studentName' : IDL.Text,
    'date' : IDL.Int,
    'parentPhone' : IDL.Text,
    'message' : IDL.Text,
    'parentName' : IDL.Text,
    'gradeApplyingFor' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'id' : AnnouncementId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Int,
    'category' : AnnouncementCategory,
  });
  const ContactId = IDL.Nat;
  const ContactForm = IDL.Record({
    'id' : ContactId,
    'subject' : IDL.Text,
    'date' : IDL.Int,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, AnnouncementCategory],
        [],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([AnnouncementId], [], []),
    'getAllAdmissionForms' : IDL.Func([], [IDL.Vec(AdmissionForm)], ['query']),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getAnnouncementsByCategory' : IDL.Func(
        [AnnouncementCategory],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'submitAdmissionForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };